package com.lge.launcher3.config;

import android.os.Build;

/* JADX INFO: loaded from: classes.dex */
public final class LauncherConst {
    public static final String ACTION_CONTROL_DUAL_RECENT = "com.lge.systemui.action.ACTION_CONTROL_DUAL_RECENT";
    public static final String ACTION_CONTROL_START_DUAL_RECENT = "com.lge.systemui.action.RECENTS_STARTED_IN_COVER_DISPLAY";
    public static final String ACTION_GESTURE_TARGET = "com.lge.launcher3.action.GESTURE_TARGET";
    public static final int ALLAPPS_EDIT = 4;
    public static final int ALLAPPS_GBOARD = 9;
    public static final int ALLAPPS_GROUP = 0;
    public static final int ALLAPPS_GROUP_ICONCHANGE = 5;
    public static final int ALLAPPS_GROUP_ICONCHANGE_GUIDE = 7;
    public static final int ALLAPPS_HIDE_APPS = 3;
    public static final int ALLAPPS_ICONCHANGE_DELETE_ICON = 6;
    public static final int ALLAPPS_ICONCHANGE_HELP = 8;
    public static final int ALLAPPS_SEARCH = 1;
    public static final int ALLAPPS_SORT = 2;
    public static final String ANDROID_PHONE_CLASS_NAME = "com.android.contacts.activities.DialtactsActivity";
    public static final String ANDROID_PHONE_PACKAGE_NAME = "com.android.contacts";
    public static String CONTEXTUAL_NAVIGATION_ACTION_NAME = null;
    public static final String CUSTOMIZE_APPICONS_SHARED_PREF_NAME = "customize_appicons_shared_prefs";
    public static final String DB_HOME_PREF_KEY_APPBOX_RELOAD = "appbox_reload";
    public static final String DB_HOME_PREF_VALUE_NONE = "none";
    public static final String DB_HOME_PREF_VALUE_RELOAD_FINISHED = "reload_finished";
    public static final int DIALOG_ALLAPPS_APPINFO = 2;
    public static final int DIALOG_ALLAPPS_LAYER_TYPE = 4;
    public static final int DIALOG_ALLAPPS_MENU_TYPE = 5;
    public static final int DIALOG_ALLAPPS_SELECT_STYLE = 1;
    public static final int DIALOG_ALLAPPS_SORT = 6;
    public static final int DIALOG_ALLAPPS_UNINSTALL = 3;
    public static final String EASYHOME_PACKAGENAME = "com.lge.easyhome";
    public static final String EXTRA_APP_NAME = "appName";
    public static final String EXTRA_CLASS_NAME = "className";
    public static final String EXTRA_NO_ICON_FRAMES = "no_icon_frames";
    public static final String EXTRA_PACKAGE_NAME = "packageName";
    public static final String GOOGLE_SEARCH_WIDGET_PACKAGENAME = "com.google.android.googlequicksearchbox";
    public static final int HOME_APPDRAWER = 1;
    public static final int HOME_DEFAULT = 0;
    public static final int HOME_EASYHOME = 2;
    public static final String HOME_INTENT_DRAGGING_END = "com.lge.launcher2.DRAGGING_STOPPED";
    public static final String HOME_INTENT_DRAGGING_STARTED = "com.lge.launcher2.DRAGGING_STARTED";
    public static final int HOME_UNKNOWN = -1;
    public static final String KEY_ICON_RESOURCE_NAME = "iconResName";
    public static final String KEY_TITLE_RESOURCE_NAME = "titleResName";
    public static final String KEY_TITLE_VALUE = "titleValue";
    public static final String LGHOME4_PACKAGENAME = "com.lge.launcher2";
    public static final String LGHOME_APP_NAME = "LGHome6";
    public static final String LGHOME_DEFAULT_HOME = "lghome_default_home";
    public static final String LGHOME_PACKAGENAME = "com.lge.launcher3";
    public static final String LGHOME_THEME_OPTIMUS = "com.lge.launcher2.theme.optimus";
    public static final String PACKAGE_NAME_LGE = "com.lge";
    public static final String PACKAGE_NAME_NATIVE = "android";
    public static final String PARAMETER_INITID = "initId";
    public static final String PARAMETER_NOTIFY = "notify";
    public static final String PERM_PREFERENCES_FILE_NANE = "com.lge.launcher3.perm_prefs";
    public static final String PERM_PREFERENCES_KEY_ALLAPPS_DISABLED = "allapps_disabled";
    public static final String PERM_PREFERENCES_KEY_EASYHOME_DISABLED = "easyhome_disabled";
    public static final String PERM_PREFERENCES_KEY_SWIVELHOME_ENABLED = "swivelhome_enabled";
    public static final String PROPERTY_PERSIST_SYS_FIRST_BOOT;
    public static final String PROPERTY_PERSIST_SYS_FIRST_MCC;
    public static final String PROPERTY_PERSIST_SYS_MCC_LIST;
    public static final String PROPERTY_RO_BUILD_TARGET_OPERATOR;
    public static final String PROPERTY_RO_CARRIER_CODE;
    public static final String PROPERTY_RO_LGE_HYDRA;
    public static final String PROPERTY_SYS_KNOCKON_KNOCKOFF_DISTANCE;
    public static final int REQUEST_CALL_PHONE_PERMISSION = 1111;
    public static final int REQUEST_EXECUTE_INAPPS = 1115;
    public static final int REQUEST_EXECUTE_SWIPEUP_APPDRAWER = 1116;
    public static final int REQUEST_FOLDERPLUS = 1112;
    public static final String RESOURCE_ARRAY_TYPE = "array";
    public static final String RESOURCE_IMAGE_TYPE = "drawable";
    public static final String RESOURCE_INTEGER_TYPE = "integer";
    public static final int RESULT_ABNORMAL_CLOSE_FOLDER = 1113;
    public static final int RESULT_OK_FOLDER_ACTIVITY = 1114;
    public static final String SKT_PHONE_CLASS_NAME = "com.skt.prod.dialer.activities.main.MainActivity";
    public static final String SKT_PHONE_CONTACT_CLASS_NAME = "com.skt.prod.phonebook.activity.main.MainActivity";
    public static final String SKT_PHONE_CONTACT_PACKAGE_NAME = "com.skt.prod.phonebook";
    public static final int SKT_PHONE_MODE_NONE = 2;
    public static final int SKT_PHONE_MODE_OEM = 0;
    public static final int SKT_PHONE_MODE_OSUPGRADE = 3;
    public static final int SKT_PHONE_MODE_T_PHONE = 1;
    public static final String SKT_PHONE_PACKAGE_NAME = "com.skt.prod.dialer";
    public static final String TABLE_FAVORITES = "favorites";

    static {
        PROPERTY_RO_CARRIER_CODE = Build.VERSION.SDK_INT < 28 ? "ro.carrier_code" : "ro.boot.product.lge.carrier_code";
        PROPERTY_RO_LGE_HYDRA = Build.VERSION.SDK_INT < 28 ? "ro.lge.hydra" : "ro.boot.vendor.lge.hydra";
        PROPERTY_RO_BUILD_TARGET_OPERATOR = Build.VERSION.SDK_INT < 28 ? "ro.build.target_operator" : "ro.vendor.lge.build.target_operator";
        PROPERTY_PERSIST_SYS_FIRST_BOOT = Build.VERSION.SDK_INT < 28 ? "persist.sys.first-boot" : "persist.vendor.lge.first-boot";
        PROPERTY_PERSIST_SYS_FIRST_MCC = Build.VERSION.SDK_INT < 28 ? "persist.sys.first-mcc" : "persist.vendor.lge.first-mcc";
        PROPERTY_PERSIST_SYS_MCC_LIST = Build.VERSION.SDK_INT < 28 ? "persist.sys.mcc-list" : "persist.vendor.lge.mcc-list";
        PROPERTY_SYS_KNOCKON_KNOCKOFF_DISTANCE = Build.VERSION.SDK_INT < 28 ? "sys.knockon.knockoff.distance" : "product.lge.sys.knockon.knockoff.distance";
        CONTEXTUAL_NAVIGATION_ACTION_NAME = "com.lge.contextualnavigationbar.ACTION_SHOW_NAVI";
    }
}
